version: '3.7'
services:
    zookeeper:
      image: zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      volumes:
        - zookeeper-data:/var/lib/zookeeper/data \
        - zookeeper-log:/var/lib/zookeeper/log \
      ports:
        - '2181:2181'
      networks:
        - kafka-net
    kafka:
      image: bitnami/kafka:latest
      environment:
        - TZ=UTC
        - KAFKA_ADVERTISED_HOST_NAME=kafka:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      ports:
        - '9092:9092'
        - '9094:9094'
      depends_on:
        - zookeeper
      networks:
        - kafka-net
      volumes:
        - kafka:/var/lib/kafka/data
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command:
      - --log-bin-trust-function-creators=ON
      - --lower_case_table_names=1
    environment:
      - MARIADB_DATABASE=test
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
      - MARIADB_ROOT_PASSWORD=test
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      kafka-net:

networks:
  kafka-net:

volumes:
  kafka:
  zookeeper-log:
  zookeeper-data:

